### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by fmartin2912** [balta2ar/brotab#9] opened 2019-12-08 10:41 UTC
Hi brotab-users,
I have a python-script that shows 3 different pages in a browser on a "kiosk". It worked fine for weeks, but since last week it produces a HTTP Error 500. 

I checked it ('bt list')on the shell: same result: 
1. first call of 'bt list' returns 7 "entries": f / i / r / e / f / o / x
2. second call of 'bt list' returns error
(see the attached file)
[brotab-bug.txt](https://github.com/balta2ar/brotab/files/3936111/brotab-bug.txt)

Can you help me?

Greetings
Martin

**Comment by balta2ar** [comment] 2019-12-08 14:51
Make sure you're using versions that match. For now it should version 0.0.5 for console client (pip), and 1.0.5 for the browser extension. If versions are ok, after you reproduce the issue, share few latest lines from the logs: /tmp/brotab.log and /tmp/brotab_mediator.log

**Comment by balta2ar** [comment] 2019-12-11 08:34
version 1.0.6 is now available

**Comment by balta2ar** [comment] 2019-12-15 10:44
I cannot reproduce this and I'm closing this. Feel free to comment if you're still experiencing issues.

**Closed by balta2ar** 2019-12-15 10:44 UTC
